### ISSUE TITLE
Adds copyright in `dotenv.sh`?

### ISSUE THREAD

**Issue by haolian9** [madcoda/dotenv-shell#4]
Since we only use the `dotenv.sh` and download it directlly.

**Comment by madcoda** [comment]
You mean adding license in the shell script? I don't know if it Is necessary.
Any reference in other projects? thanks

**Comment by haolian9** [comment]
Yes, something like [this](https://github.com/grml/grml-tips/blob/master/grml-tips#L2-L7), including author, repo url, license, and others thing you want users to know.

This also will help users find a way to feedback.

**Comment by madcoda** [comment]
thanks for you suggestion, added
